# Usage
#   Start:          docker compose up
#   With helpers:   docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker compose down
#   Destroy:        docker compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

name: petercat
version: "1.0"

services:
  backend-core:
    image: petercat-backend-base
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.aws.lambda
    restart: always
    ports:
      - 8080:8080
    environment:
      AWS_SECRET_NAME: ${AWS_SECRET_NAME}
      AWS_REGION_NAME: ${AWS_REGION_NAME}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      API_URL: ${API_URL}
      WEB_URL: ${WEB_URL}
      X_GITHUB_APP_ID: ${X_GITHUB_APP_ID}
      X_GITHUB_APPS_CLIENT_ID: ${X_GITHUB_APPS_CLIENT_ID}
      X_GITHUB_APPS_CLIENT_SECRET: ${X_GITHUB_APPS_CLIENT_SECRET}
      API_IDENTIFIER: ${API_IDENTIFIER}
      FASTAPI_SECRET_KEY: ${FASTAPI_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}